root@ubuntu-master01:~/k8s/volumes# cat pv.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes# cat pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclaim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes#
root@ubuntu-master01:~/k8s/volumes# cat pvc-demo.yml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
   - image: alpine
     name: alpine-cont
     command: ["/bin/sh", "-c"]
     args: ["hostname >> /opt/info.log; date >> /opt/info.log; sleep 2000"]
     volumeMounts:
      - name: external-vol
        mountPath: /opt
  volumes:
   - name: external-vol
     persistentVolumeClaim:
       claimName: pvclaim1
root@ubuntu-master01:~/k8s/volumes#
