root@ubuntu-master01:~/k8s/config-secrets# cat mysql-clear.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-demo
  labels:
    app: mysqlapp-dep
spec:
  selector:
    matchLabels:
      app: mysqlapp-pod
  template:
    metadata:
      labels:
        app: mysqlapp-pod
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-cont
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Demo123
        ports:
        - containerPort: 3306
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets# cat config-map.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db
data:
  dbname: test-db
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets# cat secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: RGVtbzA5OA==
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets# cat mysql-secret.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-secret
  labels:
    app: mysqlsec-dep
spec:
  selector:
    matchLabels:
      app: mysqlsec-pod
  template:
    metadata:
      labels:
        app: mysqlsec-pod
    spec:
      containers:
      - image: mysql:5.7
        name: mysqlsec-cont
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-db
              key: dbname
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
root@ubuntu-master01:~/k8s/config-secrets#
